### ISSUE TITLE
Socket hangup errors with simulado v3

### ISSUE THREAD

**Issue by Diggsey** [ldabiralai/simulado#68]
I'm seeing random build failures with this error:
```
Error tags.js:18Error: socket hang upError: socket hang up
    at createHangUpError (_http_client.js:345:15)
    at Socket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Downgrading to simulado v2 fixes the problem.

**Comment by bdo** [comment]
@Diggsey could you give more details please? 

Ideally, sharing your project or creating a small project which reproduces the error would help.

**Comment by bdo** [comment]
Closing due to inactivity
